[package]
name = "platform"
version = "0.1.0"
edition = "2021"


[dependencies]
winit = "0.28.1"
raw-window-handle = "0.5.0"
glutin = "0.30.1"
glutin-winit = "0.3"
glow = "0.13"
egui = "0.26"
egui_glow = "0.26"
cpal = "0.15.2"
